export function Spinner({ label = "Working" }) {
  return (
    <div className="flex items-center gap-2 text-sm text-slate py-6">
      <span className="inline-block h-3 w-3 border-2 border-slate border-t-transparent rounded-full animate-spin" />
      {label}…
    </div>
  );
}

export function ErrorBanner({ message }) {
  if (!message) return null;
  return (
    <div className="border-l-2 border-brick bg-brick/5 px-4 py-3 text-sm text-brick">
      {message}
    </div>
  );
}

export function SourceTag({ source }) {
  const isMock = source === "mock";
  return (
    <span
      className={`font-mono text-[11px] px-1.5 py-0.5 border ${
        isMock ? "border-amber text-amber" : "border-moss text-moss"
      }`}
      title={isMock ? "Placeholder result — set OPENAI_API_KEY on the backend for a real LLM response" : "Generated by the LLM"}
    >
      {isMock ? "mock" : "llm"}
    </span>
  );
}

export function EmptyState({ title, detail }) {
  return (
    <div className="flex flex-col items-center justify-center h-full text-center px-8 py-16 text-slate">
      <p className="font-medium text-ink mb-1">{title}</p>
      {detail && <p className="text-sm max-w-sm">{detail}</p>}
    </div>
  );
}
